import "@/styles/globals.css";
import {StateProvider} from "@/context/StateContext";
import Head from "next/head";
import reducer, {initialState} from "@/context/StateReducers";

export default function App({ Component, pageProps }) {
  return (
      <StateProvider initialState={initialState} reducer={reducer}>
        <Head>
            <title>Whatsapp Clone</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.png" />
        </Head>
        <Component {...pageProps} />
      </StateProvider>
      )


}
